### ISSUE TITLE
Create logo for ReCombine

### ISSUE THREAD

**Issue by jtcrowson** [ReCombine/ReCombine#2]
Let's add a logo for ReCombine.  It should be uploaded to the github CDN (just drag the image into a comment below) then add the url as an image to the top of `README.md` (there's one already there, just replace it)

**Comment by jtcrowson** [comment]
@caseycavanagh

**Comment by jtcrowson** [comment]
Would also be nice to use a social preview (let's get a 1280x640 version for this):

<img width="659" alt="Screen Shot 2020-01-31 at 8 03 09 PM" src="https://user-images.githubusercontent.com/3779096/73584191-caea6a00-4464-11ea-9c2f-ca685c9ff3f5.png">

Also note, I dragged in the image here, and the URL is https://user-images.githubusercontent.com/3779096/73584191-caea6a00-4464-11ea-9c2f-ca685c9ff3f5.png.  As described in the issue description, this is an easy way to upload images to the GitHub CDN then use in the README.

**Comment by caseycavanagh** [comment]
![recombine_hero_gradient](https://user-images.githubusercontent.com/2394173/73594894-8bf9fa00-44e0-11ea-9bd2-835824462e88.png)
<img width="1280" alt="recombine_hero_gradient@2x" src="https://user-images.githubusercontent.com/2394173/73594895-8bf9fa00-44e0-11ea-818a-85a4d8a13d69.png">
![recombine_hero_purple](https://user-images.githubusercontent.com/2394173/73594896-8bf9fa00-44e0-11ea-84a7-a22439a4ae77.png)
<img width="1280" alt="recombine_hero_purple@2x" src="https://user-images.githubusercontent.com/2394173/73594898-8c929080-44e0-11ea-968c-0c8f34948e3c.png">
![recombine_hero_transparent](https://user-images.githubusercontent.com/2394173/73594899-8c929080-44e0-11ea-9acd-c38d11d371e1.png)
<img width="1280" alt="recombine_hero_transparent@2x" src="https://user-images.githubusercontent.com/2394173/73594900-8c929080-44e0-11ea-9963-cde28d6d8b8b.png">
![recombine_icn_gradient](https://user-images.githubusercontent.com/2394173/73594901-8d2b2700-44e0-11ea-9c63-f06e90954ed1.png)
<img width="1001" alt="recombine_icn_gradient@2x" src="https://user-images.githubusercontent.com/2394173/73594902-8d2b2700-44e0-11ea-9492-3256d8eee7cf.png">
![recombine_icn_purple](https://user-images.githubusercontent.com/2394173/73594903-8d2b2700-44e0-11ea-934d-d1373738b020.png)
<img width="1001" alt="recombine_icn_purple@2x" src="https://user-images.githubusercontent.com/2394173/73594904-8dc3bd80-44e0-11ea-8cfb-5cdb59dbc660.png">
![recombine_icn_transparent](https://user-images.githubusercontent.com/2394173/73594905-8dc3bd80-44e0-11ea-8feb-80dc11ef4277.png)
<img width="1001" alt="recombine_icn_transparent@2x" src="https://user-images.githubusercontent.com/2394173/73594906-8dc3bd80-44e0-11ea-93fc-afd781e67b71.png">

**Comment by caseycavanagh** [comment]
Three different hero options (also to spec for what is needed for social @jtcrowson)
![recombine_hero_gradient](https://user-images.githubusercontent.com/2394173/73594932-c06db600-44e0-11ea-9794-3af56ee4db88.png)
![recombine_hero_purple](https://user-images.githubusercontent.com/2394173/73594933-c06db600-44e0-11ea-8476-1286e3d9455d.png)
![recombine_hero_transparent](https://user-images.githubusercontent.com/2394173/73594934-c06db600-44e0-11ea-85e0-9b2d7268c98b.png)

**Comment by caseycavanagh** [comment]
![recombine_recombinelogo](https://user-images.githubusercontent.com/2394173/73595141-fd3aac80-44e2-11ea-8ce9-93ccdcedc618.png)

trimmed logo

**Comment by caseycavanagh** [comment]
![recombine_recombinelogo](https://user-images.githubusercontent.com/2394173/73595166-56a2db80-44e3-11ea-817e-86df1dd03555.png)

trimmed logo

**Comment by jtcrowson** [comment]
Closed by #12

**Comment by jtcrowson** [comment]
![73594933-c06db600-44e0-11ea-8476-1286e3d9455d](https://user-images.githubusercontent.com/3779096/74066231-bb1ed880-49c4-11ea-87af-6ed5957ae18f.png)
